name: nkwonnewiapp
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: any
  intl: any
  lottie: any
  shimmer: any
  logger: any
  flutter_svg: any
  image_picker: any
  url_launcher: any
  connectivity_plus: any
  cached_network_image: any
  flutter_native_splash: any
  smooth_page_indicator: any
  wakelock_plus: any #Only being used in the Dummy Data Uploader to keep screen on.
  flutter_paypal_checkout: any # Temporarily disabled due to dependency conflicts

  # Icons
  iconsax: any
  cupertino_icons: any

  # State Management
  get: any
  get_storage: any

  # Product Specific
  readmore: any
  carousel_slider: any
  flutter_rating_bar: any
  capped_progress_indicator: any

  # Firebase
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any
  google_sign_in: any
  flutter_facebook_auth: any
  firebase_crashlytics: any
  firebase_analytics: any

dependency_overrides:
  flutter_inappwebview: ^6.0.0

  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/logos/NNN-logo-white.png"
    min_sdk_android: 21


flutter:
  generate: true
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
